### ISSUE TITLE
プロンプトセレクターでプロンプトを追加することができない

### ISSUE THREAD

**Issue by XT-404** [blue-pen5805/sdweb-easy-prompt-selector#12]
こんにちは
タグでプロンプトを追加することは不可能です 
不幸にもYMLファイルを作成し、Tagフォルダに追加してしまった場合、システムは異常を検知しませんが、一方で拡張機能は機能しなくなり、反応しなくなります。
プロンプトを追加できる機能の作り方が全く理解できず、コードで制限されています ?・?

プロンプトを挿入するオプションを追加して、拡張機能でそれを考慮させることは可能なのでしょうかね。

**Comment by blue-pen5805** [comment]
すみません。内容が理解できません。
Sorry, I can't understand what you have written.

**Comment by blue-pen5805** [comment]
I don't implement to `add-tags to file` feature. (soooo difficult)

And I don't know why you are crashing.
please check your yaml format. -> https://www.yamllint.com

**Comment by XT-404** [comment]
I have already gone to the site I have checked the file format all the encoding all and identical to the basic YML file and yet the extension crashes each time a new YML file and even create empty

**Comment by XT-404** [comment]
![image](https://user-images.githubusercontent.com/128090530/228179227-7c7a4429-959a-45f4-ba91-1fd06928837f.png)
here is what it gives even via the website that you provided me

**Comment by XT-404** [comment]
![image](https://user-images.githubusercontent.com/128090530/228179600-c9c332db-62c3-4f42-a842-52cdd940aaa2.png)

**Comment by XT-404** [comment]
if I remove the test file created via his site
![image](https://user-images.githubusercontent.com/128090530/228179827-96b3a163-5648-449c-9905-4b07f9647614.png)
no more problem everything basically works the extension refuses the slightest addition of YML file

**Comment by XT-404** [comment]
oh damn I found POUAAA YESSSSS 
![image](https://user-images.githubusercontent.com/128090530/228181412-7b04ab5f-6bac-41a1-8fa5-3a4b254a184f.png)

**Comment by blue-pen5805** [comment]
solved?

**Comment by XT-404** [comment]
YES :)
