### ISSUE TITLE
Feature Request: Clicking a second time removes prompt

### ISSUE THREAD

**Issue by MrKuenning** [blue-pen5805/sdweb-easy-prompt-selector#3]
This is a neat idea, but I would love it if clicking on a tag a second time removed it from the prompt.

For example:

If I had a clothing list and selected pants it will enter `"wearing pants"` if I changed my mind and wanted to select shorts instead, I will have to edit the prompt and remove `wearing pants` and then click shorts.  It would be much more powerful if I could just click pants a second time and have it remove the words `"wearing pants"`

This becomes increasingly useful in long prompts, If I select:  Woman, Tall, Long Hair, Plaid shirt, Pants, Hiking boots... then generate an image, and think, this would look better with shorts.  I could just click on pants and it would find those words in the prompt and remove them. And then click shorts and it would add those.

**Comment by blue-pen5805** [comment]
this feature is implemented in cfffbd49c560ef01217f13a7d07a8499b7870426.
You can delete tags by right-click on the tag button.
