### ISSUE TITLE
CSS all failed with latest SD webui

### ISSUE THREAD

**Issue by butaixianran** [blue-pen5805/sdweb-easy-prompt-selector#5]
hi, with latest SD webui, it updated gradio from 3.16.2 to 3.23.0, which changes all CSS. 

All the css names you used in js, are no longer there. So UI is a mess.

Would you like to fix that for latest version of SD webui?

You can use both gradio version's css names in same node, so it will work with both version of gradio.

**Comment by blue-pen5805** [comment]
I will fix it...

**Comment by blue-pen5805** [comment]
fix in cfffbd49c560ef01217f13a7d07a8499b7870426
